version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=Ty3iqoE0FwPXqEZ+lU0M8IqrV5a7fWt6fRUMwlpBJJI=
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
